# Generated by Django 5.1.4 on 2025-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_medicalreport_explanation_alter_medicalreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
