# Generated by Django 5.1.4 on 2025-01-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_medicalreport_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='parent_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='reports.medicalreport'),
        ),
    ]
