# Generated by Django 5.1.4 on 2025-02-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_medicalreport_parent_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='category',
            field=models.CharField(choices=[('Blood Test', 'Blood Test'), ('X-Ray', 'X-Ray'), ('MRI Scan', 'MRI Scan'), ('Prescription', 'Prescription'), ('Pathology Report', 'Pathology Report'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
